[workspace]
members = ["falconeri", "falconerid", "falconeri-worker", "falconeri_common"]
resolver = "3"

[workspace.package]
version = "2.0.0-alpha.5"
authors = ["Eric Kidd <git@randomhacks.net>"]
license = "Apache-2.0 OR MIT"
edition = "2024"

[workspace.dependencies]
futures = "0.3"
jsonschema = { version = "0.55", default-features = false }
object_store = { git = "https://github.com/apache/arrow-rs-object-store.git", features = ["aws", "gcp", "fs"] }
serde = { version = "1.0.70", features = ["derive"] }
proptest = "1.11.0"
tokio = "1.42.0"
tracing = "0.1.29"
utoipa = { version = "6", features = ["chrono", "uuid"] }
